# Generated by Django 4.2.11 on 2024-05-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('gamer_tag', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(max_length=500, unique=True)),
                ('datetime', models.DateTimeField()),
                ('game', models.CharField(choices=[('Halo', 'Halo'), ('Hell Divers 2', 'Hell Divers 2'), ('VR Chat', 'VR Chat'), ('Call Of Duty', 'Call Of Duty'), ('Other', 'Other')], default='Other', max_length=20)),
                ('player_count', models.IntegerField()),
            ],
        ),
    ]
