# Generated by Django 4.2.11 on 2024-05-04 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(max_length=500, unique=True)),
                ('datetime', models.DateTimeField()),
                ('game', models.CharField(choices=[('Halo', 'Halo'), ('Hell Divers 2', 'Hell Divers 2'), ('VR Chat', 'VR Chat'), ('Call Of Duty', 'Call Of Duty'), ('Other', 'Other')], default='Other', max_length=20)),
                ('player_count', models.IntegerField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('gamer_tag', models.ForeignKey(db_column='gamer_tag', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='game_sessions.post')),
            ],
        ),
    ]
