# Generated by Django 4.2.11 on 2024-05-05 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0003_comment_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='gamer_tag',
        ),
    ]
