# Generated by Django 4.2.11 on 2024-05-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0004_rename_author_comment_gamer_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=200, unique=True), verbose_name=models.SlugField(max_length=200, unique=True)),
        ),
    ]
