# Generated by Django 4.2.11 on 2024-05-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0007_alter_comment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='joined_status',
            field=models.BooleanField(default=False, verbose_name=models.IntegerField()),
        ),
    ]
