# Generated by Django 4.2.11 on 2024-05-19 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0008_post_joined_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
