# Generated by Django 4.2.11 on 2024-05-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0009_remove_comment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='game',
            field=models.CharField(choices=[('Halo', 'Halo'), ('Hell Divers 2', 'Hell Divers 2'), ('VR Chat', 'VR Chat'), ('Call Of Duty', 'Call Of Duty'), ('Other', 'Other'), ('Apex L', 'Apex Legends'), ('Forza M', 'Forza Motasports'), ('Forza H', 'Forza Horizon'), ('Dead By Daylight', 'Dead By Daylight')], default='Other', max_length=20),
        ),
    ]
