# Generated by Django 4.2.11 on 2024-05-23 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_adminstory_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminstory',
            name='story_id',
        ),
    ]
