# Generated by Django 4.2.11 on 2024-05-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='home_page', max_length=200, unique=True)),
                ('title', models.TextField(max_length=30, unique=True)),
                ('content', models.TextField(max_length=300)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
